Algoritmo "contas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2021
Var
// Seção de Declarações das variáveis 
numero1, numero2 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero1 <- 10
numero2 <- numero1 * 2
numero1 <- numero1 + 2

Fimalgoritmo