Algoritmo "real"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2021
Var
// Seção de Declarações das variáveis 
resultado: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
resultado <- 50*3
escreval ("O resultado é: ", resultado)

Fimalgoritmo